### ISSUE TITLE
This should support PUBG Lite

### ISSUE THREAD

**Issue by c0r37py** [EZFNDEV/UEAESKeyFinder#11]
Finding the key of this game is not supported.
Shipping exe is provided.
Game was developed using ue4.18
https://www.mediafire.com/file/ap1g2ipi3wjv08s/PUBGLite-Win64-Shipping.zip/file

**Comment by Krishna117363** [comment]
How to use this

**Comment by EZFNDEV** [comment]
I think PUBG Lite uses their own way to encrypt the pak files, so I can not add support for this game
