### ISSUE TITLE
Failed To Get Aes Key UE 4.25

### ISSUE THREAD

**Issue by LievreAI** [EZFNDEV/UEAESKeyFinder#12]
@EZFNDEV 

i still have the error even once i try with latest UE we speak on 4.25

game is Blade & Soul 

and the game key is "0xD2E5F7F94E625EFE2726B5360C1039CE7CB9ABB760A94F37BB15A6DC08741656"

the tool bring that error : Failed to find any AES keys 

so ? how is that possible? maybe the game using UE 4.17

have the same error come from your tool not fron an old engine , becuse Blade & Soul using UE 4.25
you said its not work in old versions but its not even work on new engine version

**Comment by EZFNDEV** [comment]
Can you use this tool https://github.com/NtQuery/Scylla to dump both games and send it to me?

**Comment by LievreAI** [comment]
[SAOFB_dump.zip](https://github.com/EZFNDEV/UEAESKeyFinder/files/7231521/SAOFB_dump.zip)

**Comment by EZFNDEV** [comment]
That file is way too small, make sure you dump the actual game and not the launcher, the executable name should contain "-Win64-Shipping". The file size should be more than 50mbs

**Comment by LievreAI** [comment]
ok i do it again

**Comment by mrcyclo** [comment]
[https://mega.nz/file/jVh1EISY#CV44PUfkdgfH9MM85ZWUviAPyMRF4NZMQ27KdOWHouw](url)
Here is BNSR dumped file. Hope this help.

**Comment by EZFNDEV** [comment]
Thanks, I found out what was causing the problem :)

**Comment by mrcyclo** [comment]
Thank for hard work. But I think this game has more than 1 aes key because I can't unpack some .pak files with founded key. Can you help me figure that out?
