### ISSUE TITLE
SAOFB Support

### ISSUE THREAD

**Issue by LievreAI** [EZFNDEV/UEAESKeyFinder#20]
hello dear @EZFNDEV 
i check the tool now on the same game i play were i was error of the aes not found
and its still the same error so i dump the game bin with the tool

from some reason i cannot attached it so i upload to my drive the link is :
[https://drive.google.com/file/d/1oQoEaCnq7Y6cCBymYEEeznx0RVSfdDVP/view?usp=sharing](url)

**Comment by EZFNDEV** [comment]
Okay, games older than 4.18 should now work too :)

**Comment by LievreAI** [comment]
thanks @EZFNDEV Love Ya <3

**Comment by LievreAI** [comment]
say " unhandled exception. System.IndexOfRangeException: Index was outside the bounds of the array.
at Searcher.FindAllPattern(Int64& t)
at UEAesKeyFinder.Program.Main(String[] args)

**Comment by LievreAI** [comment]
![3](https://user-images.githubusercontent.com/84988313/144765329-15d713c4-7a14-4609-b5ef-21d6c6c4f378.png)

i want what wrong
