### ISSUE TITLE
Unable to find AES keys

### ISSUE THREAD

**Issue by mdo992** [EZFNDEV/UEAESKeyFinder#23]
I tried the first three methods for dumping the AES key. 

First I tried the memory option but I get the error from #21
After that I tried to dump with the File option, it returns "Failed to find any AES Keys."
Then I tried the Dump File option and I get the same error, "Failed to find any AES Keys."
The file also ends with `-Shipping-Win64.exe`

UE Version: `++UE4+Release-4.25-CL-14469661`
Game Information: https://pastebin.com/raw/KxsdHkRE

**Comment by EZFNDEV** [comment]
Works now, the key is 0x86BABDD6D5151539445C30B6709999362EA51C91B6D4845DC302C27DF92E6EEA
