### ISSUE TITLE
Failed to find any AES keys

### ISSUE THREAD

**Issue by LievreAI** [EZFNDEV/UEAESKeyFinder#6]
hey @EZFNDEV 
i am try to find AES key on game with aes key
however its cannot find one and i know there is one on it

**Comment by EZFNDEV** [comment]
Which game and engine version?

**Comment by DemonRem** [comment]
Sword Art Online Fatal Bullet 
Engine 4.17
i with another username <LievreAI> its me.

**Comment by EZFNDEV** [comment]
This tool doesnt work well with older versions, if you find the aes key, please upload a memory dump and the key

**Comment by LievreAI** [comment]
[_0000.zip](https://github.com/EZFNDEV/UEAESKeyFinder/files/6640859/_0000.zip)

**Comment by LievreAI** [comment]
@EZFNDEV the aes is "h67GrjX2aGMgrAQeNwf9VmCYbt50ylJFeP3rIhbxh4e9bZXnqm8sbvEjWGOi6rgs"
hope its will help you to solve the error
