### ISSUE TITLE
Issue opening Sonic Smackdown.

### ISSUE THREAD

**Issue by DatTaiwanGuy** [EZFNDEV/UEAESKeyFinder#9]
Had issues with this correct key for Sonic Smackdown https://arcforged.itch.io/sonic-smackdown.

**Comment by EZFNDEV** [comment]
It works fine for me
![image](https://user-images.githubusercontent.com/56506141/132948016-61423d9c-481c-4708-9a59-529b8fd2c875.png)

Key: 0x26858B259CE85E55611B355CF193CDE2348FDCAC6D4ED97B6DA861BA539BD556
